//! CLDR Data Loader
//!
//! Handles loading of CLDR locale data from embedded compile-time data
//! and runtime binary files.

const std = @import("std");
const Allocator = std.mem.Allocator;
const types = @import("types.zig");

// Import embedded data (generated by tools/cldr/extract.zig)
// The embedded_data.zig file provides a stub when data hasn't been generated
pub const embedded = @import("embedded_data.zig");

// Use the LocaleData type from embedded_data since it's auto-generated
// and may have a different structure than types.LocaleData
pub const LocaleData = embedded.LocaleData;

/// Check if a locale tag has embedded data
pub fn isEmbeddedLocale(locale_tag: []const u8) bool {
    for (embedded.locale_tags) |tag| {
        if (std.mem.eql(u8, tag, locale_tag)) {
            return true;
        }
    }
    return false;
}

/// Get embedded locale data (zero allocation)
pub fn getEmbeddedLocale(locale_tag: []const u8) ?*const LocaleData {
    return embedded.getLocale(locale_tag);
}

/// Get list of all embedded locale tags
pub fn getEmbeddedLocaleTags() []const []const u8 {
    return &embedded.locale_tags;
}

/// Load locale data from a binary file.
///
/// This is used for Tier 2 locales that are not embedded at compile time.
/// The caller owns the returned data and must call deinit() when done.
pub fn loadLocaleFromFile(allocator: Allocator, locale_tag: []const u8) !?*const LocaleData {
    // Build path to binary data file
    // Expected location: data/cldr/bin/{locale}.bin
    var path_buf: [256]u8 = undefined;
    const path = std.fmt.bufPrint(&path_buf, "data/cldr/bin/{s}.bin", .{locale_tag}) catch {
        return null;
    };

    // Try to open the file
    const file = std.fs.cwd().openFile(path, .{}) catch {
        return null;
    };
    defer file.close();

    // Read binary data and parse
    return loadFromBinary(allocator, file) catch {
        return null;
    };
}

/// Binary format header
const BinaryHeader = extern struct {
    magic: [4]u8 = .{ 'C', 'L', 'D', 'R' },
    version: u16 = 1,
    flags: u16 = 0,
    tag_offset: u32,
    tag_length: u32,
    months_offset: u32,
    weekdays_offset: u32,
    patterns_offset: u32,
    symbols_offset: u32,
};

/// Load locale data from binary format
/// TODO: This is a stub - full binary parsing not yet implemented
fn loadFromBinary(_: Allocator, file: std.fs.File) !?*const LocaleData {
    // Read header
    var header: BinaryHeader = undefined;
    const header_bytes = std.mem.asBytes(&header);
    const bytes_read = try file.readAll(header_bytes);
    if (bytes_read != @sizeOf(BinaryHeader)) {
        return null; // Invalid format
    }

    // Verify magic
    if (!std.mem.eql(u8, &header.magic, "CLDR")) {
        return null; // Invalid format
    }

    // Binary loading not yet fully implemented
    // TODO: Implement full binary parsing to load month names, weekdays, etc.
    // Return null for now - caller will fall back to embedded data
    return null;
}

/// Write locale data to binary format
pub fn writeToBinary(data: *const LocaleData, writer: anytype) !void {
    // Write header
    var header = BinaryHeader{
        .tag_offset = @sizeOf(BinaryHeader),
        .tag_length = @intCast(data.tag.len),
        .months_offset = 0, // Calculated below
        .weekdays_offset = 0,
        .patterns_offset = 0,
        .symbols_offset = 0,
    };

    // Calculate offsets
    var offset: u32 = @sizeOf(BinaryHeader);
    offset += header.tag_length;

    header.months_offset = offset;
    // ... calculate other offsets

    // Write header
    try writer.writeAll(std.mem.asBytes(&header));

    // Write tag
    try writer.writeAll(data.tag);

    // TODO: Write other sections
}

// ============================================================================
// Tests
// ============================================================================

test "isEmbeddedLocale returns false for unknown" {
    try std.testing.expect(!isEmbeddedLocale("xx-UNKNOWN"));
}

test "getEmbeddedLocale returns null for unknown" {
    const result = getEmbeddedLocale("xx-UNKNOWN");
    try std.testing.expectEqual(@as(?*const LocaleData, null), result);
}

test "loadLocaleFromFile returns null for missing file" {
    const allocator = std.testing.allocator;
    const result = try loadLocaleFromFile(allocator, "xx-MISSING");
    try std.testing.expectEqual(@as(?*const LocaleData, null), result);
}
