//! Public Suffix List Generator
//!
//! Reads data/psl/public_suffix_list.dat and generates src/public_suffix_data.zig
//! with a compile-time string map for O(1) PSL lookups.

const std = @import("std");

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    std.debug.print("[PSL Generator] Starting...\n", .{});

    // Read PSL data file
    const psl_file = "data/psl/public_suffix_list.dat";
    const psl_data = std.fs.cwd().readFileAlloc(allocator, psl_file, 10 * 1024 * 1024) catch |err| {
        std.debug.print("Error reading {s}: {}\n", .{ psl_file, err });
        return err;
    };
    defer allocator.free(psl_data);

    std.debug.print("[PSL Generator] Read {d} bytes from {s}\n", .{ psl_data.len, psl_file });

    // Generate Zig source code directly
    var output = std.ArrayList(u8){};
    defer output.deinit(allocator);

    const writer = output.writer(allocator);

    // Header
    try writer.writeAll(
        \\//! Public Suffix List Data (Auto-generated)
        \\//!
        \\//! DO NOT EDIT THIS FILE MANUALLY
        \\//! Generated by: tools/generate_psl.zig
        \\//! Source data: data/psl/public_suffix_list.dat
        \\
        \\const std = @import("std");
        \\
        \\/// Public Suffix List rules as a compile-time string map
        \\pub const PSL_RULES = std.StaticStringMap(void).initComptime(.{
        \\
    );

    // Parse and generate entries directly
    var lines = std.mem.splitScalar(u8, psl_data, '\n');
    var rule_count: usize = 0;

    while (lines.next()) |line| {
        const trimmed = std.mem.trim(u8, line, " \t\r");

        // Skip empty lines and comments
        if (trimmed.len == 0) continue;
        if (std.mem.startsWith(u8, trimmed, "//")) continue;

        // Write rule directly
        try writer.print("    .{{ \"{s}\", {{}} }},\n", .{trimmed});
        rule_count += 1;
    }

    std.debug.print("[PSL Generator] Processed {d} rules\n", .{rule_count});

    // Footer
    try writer.writeAll(
        \\});
        \\
        \\/// Total number of PSL rules
        \\pub const PSL_RULE_COUNT: usize = 
    );
    try writer.print("{d};\n", .{rule_count});

    // Write generated file
    const output_file = "src/public_suffix_data.zig";
    try std.fs.cwd().writeFile(.{
        .sub_path = output_file,
        .data = output.items,
    });

    std.debug.print("[PSL Generator] ✓ Generated {s} ({d} bytes, {d} rules)\n", .{
        output_file,
        output.items.len,
        rule_count,
    });

    std.debug.print("[PSL Generator] Complete!\n", .{});
}
