//! DOM Interface WrapperTypeInfo Definitions
//!
//! This module defines WrapperTypeInfo for core DOM interfaces.
//! Eventually these will be generated by codegen, but for now they're
//! manually defined to enable type-safe V8 bindings.
//!
//! ## Tag Assignment
//!
//! Tags are assigned to form contiguous ranges for inheritance checking:
//!
//! ```
//! EventTarget (100, max: 899)
//!   └─ Node (110, max: 889)
//!       ├─ Element (120, max: 599)
//!       │   └─ HTMLElement (130, max: 500)
//!       │       ├─ HTMLDivElement (140)
//!       │       ├─ HTMLSpanElement (141)
//!       │       └─ ... other HTML elements
//!       ├─ CharacterData (600, max: 650)
//!       │   ├─ Text (610)
//!       │   │   └─ CDATASection (611)
//!       │   ├─ Comment (620)
//!       │   └─ ProcessingInstruction (621)
//!       ├─ DocumentFragment (700, max: 750)
//!       │   └─ ShadowRoot (710)
//!       ├─ DocumentType (800)
//!       └─ Document (810, max: 850)
//!           ├─ HTMLDocument (820)
//!           └─ XMLDocument (821)
//! ```

const std = @import("std");
const wrapper_type_info = @import("wrapper_type_info.zig");
const WrapperTypeInfo = wrapper_type_info.WrapperTypeInfo;
const TypeTag = wrapper_type_info.TypeTag;
const WrapperClassId = wrapper_type_info.WrapperClassId;
const IdlDefinitionKind = wrapper_type_info.IdlDefinitionKind;
const v8 = @import("ffi.zig");

// ============================================================================
// Placeholder install functions (these would normally be generated)
// ============================================================================

fn placeholderInstall(_: *v8.Isolate) *v8.FunctionTemplate {
    // INTENTIONAL PANIC: This is a placeholder for codegen-generated implementations.
    // If this code path is reached, it means:
    // 1. Code is trying to use a DOM interface before codegen has run
    // 2. Or the interface is being used but its template hasn't been generated yet
    //
    // This is a programming error, not a runtime error that should be recoverable.
    // The correct fix is to run codegen to generate the real implementations.
    //
    // Note: We use @panic here instead of unreachable because unreachable in
    // ReleaseFast is undefined behavior, while @panic always produces a crash
    // with a clear message.
    @panic("WrapperTypeInfo.install_template_fn called but not implemented - run codegen to generate implementations");
}

// ============================================================================
// EventTarget hierarchy
// ============================================================================

pub const EventTarget_type_info = WrapperTypeInfo{
    .interface_name = "EventTarget",
    .parent = null,
    .this_tag = 100,
    .max_subclass_tag = 899, // Covers Node, Window, and all descendants
    .wrapper_class_id = .object,
    .idl_definition_kind = .interface,
    .install_template_fn = placeholderInstall,
};

// ============================================================================
// Window (Global object) - inherits from EventTarget
// ============================================================================

pub const Window_type_info = WrapperTypeInfo{
    .interface_name = "Window",
    .parent = &EventTarget_type_info,
    .this_tag = 105, // Between EventTarget (100) and Node (110)
    .max_subclass_tag = 105, // Leaf node (no subclasses)
    .wrapper_class_id = .object,
    .idl_definition_kind = .interface,
    .install_template_fn = placeholderInstall,
};

// ============================================================================
// Node hierarchy
// ============================================================================

pub const Node_type_info = WrapperTypeInfo{
    .interface_name = "Node",
    .parent = &EventTarget_type_info,
    .this_tag = 110,
    .max_subclass_tag = 889, // Covers Element, CharacterData, Document, etc.
    .wrapper_class_id = .node, // Nodes get special GC treatment
    .idl_definition_kind = .interface,
    .install_template_fn = placeholderInstall,
};

// ============================================================================
// Element hierarchy
// ============================================================================

pub const Element_type_info = WrapperTypeInfo{
    .interface_name = "Element",
    .parent = &Node_type_info,
    .this_tag = 120,
    .max_subclass_tag = 599, // Covers HTMLElement and all HTML elements
    .wrapper_class_id = .node,
    .idl_definition_kind = .interface,
    .install_template_fn = placeholderInstall,
};

pub const HTMLElement_type_info = WrapperTypeInfo{
    .interface_name = "HTMLElement",
    .parent = &Element_type_info,
    .this_tag = 130,
    .max_subclass_tag = 500, // Covers all specific HTML elements
    .wrapper_class_id = .node,
    .idl_definition_kind = .interface,
    .install_template_fn = placeholderInstall,
};

pub const HTMLDivElement_type_info = WrapperTypeInfo{
    .interface_name = "HTMLDivElement",
    .parent = &HTMLElement_type_info,
    .this_tag = 140,
    .max_subclass_tag = 140, // Leaf node
    .wrapper_class_id = .node,
    .idl_definition_kind = .interface,
    .install_template_fn = placeholderInstall,
};

pub const HTMLSpanElement_type_info = WrapperTypeInfo{
    .interface_name = "HTMLSpanElement",
    .parent = &HTMLElement_type_info,
    .this_tag = 141,
    .max_subclass_tag = 141, // Leaf node
    .wrapper_class_id = .node,
    .idl_definition_kind = .interface,
    .install_template_fn = placeholderInstall,
};

// ============================================================================
// CharacterData hierarchy
// ============================================================================

pub const CharacterData_type_info = WrapperTypeInfo{
    .interface_name = "CharacterData",
    .parent = &Node_type_info,
    .this_tag = 600,
    .max_subclass_tag = 650,
    .wrapper_class_id = .node,
    .idl_definition_kind = .interface,
    .install_template_fn = placeholderInstall,
};

pub const Text_type_info = WrapperTypeInfo{
    .interface_name = "Text",
    .parent = &CharacterData_type_info,
    .this_tag = 610,
    .max_subclass_tag = 619, // Room for CDATASection
    .wrapper_class_id = .node,
    .idl_definition_kind = .interface,
    .install_template_fn = placeholderInstall,
};

pub const CDATASection_type_info = WrapperTypeInfo{
    .interface_name = "CDATASection",
    .parent = &Text_type_info,
    .this_tag = 611,
    .max_subclass_tag = 611, // Leaf node
    .wrapper_class_id = .node,
    .idl_definition_kind = .interface,
    .install_template_fn = placeholderInstall,
};

pub const Comment_type_info = WrapperTypeInfo{
    .interface_name = "Comment",
    .parent = &CharacterData_type_info,
    .this_tag = 620,
    .max_subclass_tag = 620, // Leaf node
    .wrapper_class_id = .node,
    .idl_definition_kind = .interface,
    .install_template_fn = placeholderInstall,
};

pub const ProcessingInstruction_type_info = WrapperTypeInfo{
    .interface_name = "ProcessingInstruction",
    .parent = &CharacterData_type_info,
    .this_tag = 621,
    .max_subclass_tag = 621, // Leaf node
    .wrapper_class_id = .node,
    .idl_definition_kind = .interface,
    .install_template_fn = placeholderInstall,
};

// ============================================================================
// DocumentFragment hierarchy
// ============================================================================

pub const DocumentFragment_type_info = WrapperTypeInfo{
    .interface_name = "DocumentFragment",
    .parent = &Node_type_info,
    .this_tag = 700,
    .max_subclass_tag = 750,
    .wrapper_class_id = .node,
    .idl_definition_kind = .interface,
    .install_template_fn = placeholderInstall,
};

pub const ShadowRoot_type_info = WrapperTypeInfo{
    .interface_name = "ShadowRoot",
    .parent = &DocumentFragment_type_info,
    .this_tag = 710,
    .max_subclass_tag = 710, // Leaf node
    .wrapper_class_id = .node,
    .idl_definition_kind = .interface,
    .install_template_fn = placeholderInstall,
};

// ============================================================================
// DocumentType
// ============================================================================

pub const DocumentType_type_info = WrapperTypeInfo{
    .interface_name = "DocumentType",
    .parent = &Node_type_info,
    .this_tag = 800,
    .max_subclass_tag = 800, // Leaf node
    .wrapper_class_id = .node,
    .idl_definition_kind = .interface,
    .install_template_fn = placeholderInstall,
};

// ============================================================================
// Document hierarchy
// ============================================================================

pub const Document_type_info = WrapperTypeInfo{
    .interface_name = "Document",
    .parent = &Node_type_info,
    .this_tag = 810,
    .max_subclass_tag = 850,
    .wrapper_class_id = .node,
    .idl_definition_kind = .interface,
    .install_template_fn = placeholderInstall,
};

pub const HTMLDocument_type_info = WrapperTypeInfo{
    .interface_name = "HTMLDocument",
    .parent = &Document_type_info,
    .this_tag = 820,
    .max_subclass_tag = 820, // Leaf node
    .wrapper_class_id = .node,
    .idl_definition_kind = .interface,
    .install_template_fn = placeholderInstall,
};

pub const XMLDocument_type_info = WrapperTypeInfo{
    .interface_name = "XMLDocument",
    .parent = &Document_type_info,
    .this_tag = 821,
    .max_subclass_tag = 821, // Leaf node
    .wrapper_class_id = .node,
    .idl_definition_kind = .interface,
    .install_template_fn = placeholderInstall,
};

// ============================================================================
// Non-Node interfaces
// ============================================================================

pub const Event_type_info = WrapperTypeInfo{
    .interface_name = "Event",
    .parent = null,
    .this_tag = 1000,
    .max_subclass_tag = 1100, // Room for CustomEvent, UIEvent, etc.
    .wrapper_class_id = .object,
    .idl_definition_kind = .interface,
    .install_template_fn = placeholderInstall,
};

pub const CustomEvent_type_info = WrapperTypeInfo{
    .interface_name = "CustomEvent",
    .parent = &Event_type_info,
    .this_tag = 1010,
    .max_subclass_tag = 1010, // Leaf node
    .wrapper_class_id = .object,
    .idl_definition_kind = .interface,
    .install_template_fn = placeholderInstall,
};

// ============================================================================
// URL interfaces
// ============================================================================

pub const URL_type_info = WrapperTypeInfo{
    .interface_name = "URL",
    .parent = null,
    .this_tag = 1200,
    .max_subclass_tag = 1200, // Leaf node
    .wrapper_class_id = .object,
    .idl_definition_kind = .interface,
    .install_template_fn = placeholderInstall,
};

pub const URLSearchParams_type_info = WrapperTypeInfo{
    .interface_name = "URLSearchParams",
    .parent = null,
    .this_tag = 1210,
    .max_subclass_tag = 1210, // Leaf node
    .wrapper_class_id = .object,
    .idl_definition_kind = .interface,
    .install_template_fn = placeholderInstall,
};

// ============================================================================
// MessagePort and MessageChannel (HTML messaging)
// ============================================================================

pub const MessagePort_type_info = WrapperTypeInfo{
    .interface_name = "MessagePort",
    .parent = &EventTarget_type_info, // MessagePort is an EventTarget
    .this_tag = 1220,
    .max_subclass_tag = 1220, // Leaf node
    .wrapper_class_id = .object,
    .idl_definition_kind = .interface,
    .install_template_fn = placeholderInstall,
};

pub const MessageChannel_type_info = WrapperTypeInfo{
    .interface_name = "MessageChannel",
    .parent = null, // MessageChannel is NOT an EventTarget
    .this_tag = 1230,
    .max_subclass_tag = 1230, // Leaf node
    .wrapper_class_id = .object,
    .idl_definition_kind = .interface,
    .install_template_fn = placeholderInstall,
};

// ============================================================================
// Helper functions
// ============================================================================

/// Get WrapperTypeInfo by interface name
pub fn getTypeInfoByName(name: []const u8) ?*const WrapperTypeInfo {
    const type_infos = [_]*const WrapperTypeInfo{
        &EventTarget_type_info,
        &Window_type_info,
        &Node_type_info,
        &Element_type_info,
        &HTMLElement_type_info,
        &HTMLDivElement_type_info,
        &HTMLSpanElement_type_info,
        &CharacterData_type_info,
        &Text_type_info,
        &CDATASection_type_info,
        &Comment_type_info,
        &ProcessingInstruction_type_info,
        &DocumentFragment_type_info,
        &ShadowRoot_type_info,
        &DocumentType_type_info,
        &Document_type_info,
        &HTMLDocument_type_info,
        &XMLDocument_type_info,
        &Event_type_info,
        &CustomEvent_type_info,
        &URL_type_info,
        &URLSearchParams_type_info,
        &MessagePort_type_info,
        &MessageChannel_type_info,
    };

    for (type_infos) |info| {
        if (std.mem.eql(u8, info.getName(), name)) {
            return info;
        }
    }
    return null;
}

// ============================================================================
// Tests
// ============================================================================

test "DOM type info hierarchy" {
    const testing = std.testing;

    // Test inheritance chain
    try testing.expect(HTMLDivElement_type_info.isSubclassOf(&HTMLElement_type_info));
    try testing.expect(HTMLDivElement_type_info.isSubclassOf(&Element_type_info));
    try testing.expect(HTMLDivElement_type_info.isSubclassOf(&Node_type_info));
    try testing.expect(HTMLDivElement_type_info.isSubclassOf(&EventTarget_type_info));

    // Test non-inheritance
    try testing.expect(!Element_type_info.isSubclassOf(&Document_type_info));
    try testing.expect(!Event_type_info.isSubclassOf(&Node_type_info));
}

test "DOM type info tag ranges" {
    const testing = std.testing;

    // Test tag range checking
    // Node should accept Element, Document, Text, etc.
    try testing.expect(Node_type_info.isValidTag(Element_type_info.this_tag));
    try testing.expect(Node_type_info.isValidTag(Document_type_info.this_tag));
    try testing.expect(Node_type_info.isValidTag(Text_type_info.this_tag));

    // EventTarget should accept Node and all descendants
    try testing.expect(EventTarget_type_info.isValidTag(Node_type_info.this_tag));
    try testing.expect(EventTarget_type_info.isValidTag(HTMLDivElement_type_info.this_tag));

    // But Node should NOT accept Event (outside its range)
    try testing.expect(!Node_type_info.isValidTag(Event_type_info.this_tag));
}

test "getTypeInfoByName" {
    const testing = std.testing;

    const element_info = getTypeInfoByName("Element");
    try testing.expect(element_info != null);
    try testing.expectEqual(@as(TypeTag, 120), element_info.?.this_tag);

    const unknown = getTypeInfoByName("Unknown");
    try testing.expect(unknown == null);
}
