// Auto-generated by zoop-codegen
// DO NOT EDIT - changes will be overwritten
//
// This file was generated from the source file with the same name.
// Class definitions have been enhanced with:
//   - Inherited methods from parent classes
//   - Property getters and setters
//   - Optimized field layouts

//! CountQueuingStrategy class per WHATWG Streams Standard
//!
//! Spec: https://streams.spec.whatwg.org/#cqs-class
//! IDL: specs/streams.idl lines 219-225
//!
//! A queuing strategy that counts chunks (size always 1).

const std = @import("std");
const webidl = @import("webidl");
/// CountQueuingStrategy zoop class
/// 
/// IDL:
/// ```webidl
/// [Exposed=*]
/// interface CountQueuingStrategy {
/// constructor(QueuingStrategyInit init);
/// 
/// readonly attribute unrestricted double highWaterMark;
/// readonly attribute Function size;
/// };
/// ```
pub const CountQueuingStrategy = struct {
    allocator: std.mem.Allocator,
    /// [[highWaterMark]]: High water mark value
    high_water_mark: f64,

    /// Initialize a new CountQueuingStrategy (internal - not exposed via WebIDL)
    /// 
    /// The constructor is handled by zoop codegen
    pub fn init(allocator: std.mem.Allocator, high_water_mark: f64) CountQueuingStrategy {
        return .{
            .allocator = allocator,
            .high_water_mark = high_water_mark,
        };
    }
    pub fn deinit(self: *CountQueuingStrategy) void {
        _ = self;
        // No heap allocations to clean up
    }
    /// Returns the high water mark provided to the constructor.
    /// 
    /// IDL: readonly attribute unrestricted double highWaterMark;
    /// 
    /// Spec algorithm: § 7.3.3 "The highWaterMark getter steps are:"
    pub fn get_highWaterMark(self: *const CountQueuingStrategy) f64 {
        // Step 1: Return this.[[highWaterMark]].
        return self.high_water_mark;
    }
    /// Returns the size function (countSizeFunction).
    /// 
    /// IDL: readonly attribute Function size;
    /// 
    /// Spec algorithm: § 7.3.3 "The size getter steps are:"
    pub fn get_size(self: *const CountQueuingStrategy) webidl.JSValue {
        // Step 1: Return this's relevant global object's count queuing strategy size function.
        // In full implementation, would return a proper Function WebIDL type
        // For now, return a placeholder
        _ = self;
        return webidl.JSValue{ .undefined = {} };
    }
    /// Size algorithm implementation (not part of WebIDL interface)
    /// 
    /// This is the actual size function referenced by get_size
    /// 
    /// Spec: § 7.3.4 "Count queuing strategy size function"
    pub fn sizeAlgorithm(chunk: webidl.JSValue) f64 {
        // Step 1: Return 1.
        _ = chunk;
        return 1.0;
    }
};

