// Auto-generated by webidl-codegen
// DO NOT EDIT - changes will be overwritten
//
// This file was generated from the source file with the same name.
// Class definitions have been enhanced with:
//   - Inherited methods from parent classes
//   - Property getters and setters
//   - Optimized field layouts

const std = @import("std");
const webidl = @import("webidl");

/// TextDecodeOptions dictionary
///
/// WHATWG Encoding Standard § 5
/// https://encoding.spec.whatwg.org/#dictdef-textdecodeoptions
///
/// IDL:
/// ```
/// dictionary TextDecodeOptions {
///   boolean stream = false;
/// };
/// ```
pub const TextDecodeOptions = struct {
    /// WebIDL: boolean
    stream: webidl.boolean = false,
};
