// Auto-generated by webidl-codegen
// DO NOT EDIT - changes will be overwritten
//
// This file was generated from the source file with the same name.
// Class definitions have been enhanced with:
//   - Inherited methods from parent classes
//   - Property getters and setters
//   - Optimized field layouts

const std = @import("std");
const webidl = @import("webidl");

/// TextDecoderOptions dictionary
///
/// WHATWG Encoding Standard § 5
/// https://encoding.spec.whatwg.org/#dictdef-textdecoderoptions
///
/// IDL:
/// ```
/// dictionary TextDecoderOptions {
///   boolean fatal = false;
///   boolean ignoreBOM = false;
/// };
/// ```
pub const TextDecoderOptions = struct {
    /// WebIDL: boolean
    fatal: webidl.boolean = false,

    /// WebIDL: boolean
    ignoreBOM: webidl.boolean = false,
};
