// Auto-generated by webidl-codegen
// DO NOT EDIT - changes will be overwritten
//
// This file was generated from the source file with the same name.
// Class definitions have been enhanced with:
//   - Inherited methods from parent classes
//   - Property getters and setters
//   - Optimized field layouts

const std = @import("std");

const webidl = @import("webidl");
/// TextEncoderCommon mixin
/// 
/// WHATWG Encoding Standard § 5
/// https://encoding.spec.whatwg.org/#interface-mixin-textencodercommon
/// 
/// IDL:
/// ```
/// interface mixin TextEncoderCommon {
/// readonly attribute DOMString encoding;
/// };
/// ```
/// 
/// Note: This mixin is not used by TextEncoder implementation,
/// as the property is implemented directly in TextEncoder.
/// The encoding property type is webidl.DOMString.
pub const TextEncoderCommon = struct {
    encoding: webidl.DOMString,
    pub inline fn get_encoding(self: *const @This()) webidl.DOMString {
        return self.encoding;
    }
};

