// Auto-generated by webidl-codegen
// DO NOT EDIT - changes will be overwritten
//
// This file was generated from the source file with the same name.
// Class definitions have been enhanced with:
//   - Inherited methods from parent classes
//   - Property getters and setters
//   - Optimized field layouts

const std = @import("std");
const webidl = @import("webidl");

/// TextDecoderCommon mixin
///
/// WHATWG Encoding Standard § 5
/// https://encoding.spec.whatwg.org/#interface-mixin-textdecodercommon
///
/// IDL:
/// ```
/// interface mixin TextDecoderCommon {
///   readonly attribute DOMString encoding;
///   readonly attribute boolean fatal;
///   readonly attribute boolean ignoreBOM;
/// };
/// ```
///
/// Note: This mixin is not used by TextDecoder implementation,
/// as the properties are implemented directly in TextDecoder.
pub const TextDecoderCommon = struct {
    /// WebIDL: DOMString
    encoding: webidl.DOMString,

    /// WebIDL: boolean
    fatal: webidl.boolean,

    /// WebIDL: boolean
    ignoreBOM: webidl.boolean,
};
